```
                                                                    .___ ______________________  _________________
                                                                    |   |\__    ___/\_   _____/ /   _____/\_____  \
                                                                    |   |  |    |    |    __)_  \_____  \  /   |   \
                                                                    |   |  |    |    |        \ /        \/    |    \
                                                                    |___|  |____|   /_______  //_______  /\_______  /
                                                                                            \/         \/         \/
```
<div class="alert alert-block alert-info">
<span style="color: rgb(0,53,91);">
<font face = "Times New Roman" size = "6"><b><center>Programacion para Mineria de Datos</center></b></font>
<font face = "Times New Roman" size = "5"><b><center>EJERCICIO_2_NUMPY_ARRAY</center></b></font>

<b><font back = "Times New Roman" size = "4"><center>Unidad 3: </center></font>

<div align="right"><font face = "Times New Roman" size = "2">Mtro. Miguel Tlapa Juarez (migueltlapa@iteso.mx)</font></div>
</span></div>



# Ejercicios Prácticos de NumPy: Arrays

**Instrucciones:** Utiliza tus conocimientos de NumPy para resolver los siguientes problemas. Escribe el código necesario en las celdas correspondientes para obtener el resultado solicitado.


### Sección 1: Creación de Arrays (`arange` y `linspace`)

### Sección 1: Generación de Números Aleatorios

1.  **Entero único:** Simula el lanzamiento de un dado de 6 caras. Genera un único número entero aleatorio entre 1 y 6 (ambos inclusive).
2.  **Array de flotantes:** Crea un array de NumPy con 8 números flotantes aleatorios, donde cada número esté entre 0.0 y 1.0.
3.  **Matriz de enteros:** Crea una matriz (array 2D) de 3x4 que contenga números enteros aleatorios entre 10 y 50 (sin incluir el 50).

In [ ]:
import numpy as np
# Espacio para tus respuestas de la Sección 1

### Sección 2: Dimensiones y Forma (`ndim`, `shape` y `reshape`)

1.  **Creación y análisis 2D:**
    * Crea un array 2D (una matriz) de 3 filas y 4 columnas con los números del 0 al 11.
    * Imprime la forma (`shape`) del array.
    * Imprime el número de dimensiones (`ndim`) del array.
2.  **Creación y análisis 3D:**
    * Crea un array 3D de dimensiones (2, 3, 2) utilizando los números del 0 al 11.
    * Imprime su forma y el número de dimensiones.

In [ ]:
# Espacio para tus respuestas de la Sección 2

### Sección 3: Indexación y Slicing

Para los siguientes ejercicios, utiliza el array `M` que se define en la celda de abajo:

In [ ]:
M = np.arange(25).reshape(5, 5)
print("Array M:")
print(M)

1.  **Elemento específico:** Obtén el número `18` del array `M`.
2.  **Fila completa:** Obtén la segunda fila completa del array `M` (la que contiene los números del 5 al 9).
3.  **Columna completa:** Obtén la última columna del array `M` (la que contiene 4, 9, 14, 19, 24).
4.  **Submatriz (Slicing 2D):** Obtén la submatriz que contiene los números:
    ```
    [[11, 12],
     [16, 17]]
    ```
5.  **Slicing con pasos:** A partir de `M`, obtén el siguiente resultado saltando filas y columnas:
    ```
    [[ 0  2  4],
     [10 12 14],
     [20 22 24]]
    ```

In [ ]:
# Espacio para tus respuestas de la Sección 3

### Sección 4: Vistas vs. Copias

1.  **Predice el resultado:** Observa el siguiente código. ¿Qué se imprimirá al final? Explica brevemente por qué.
    ```python
    A = np.arange(10)
    B = A[3:7]
    B[0] = 99
    print(A)
    ```
2.  **Soluciona el problema:** Modifica el código anterior utilizando `.copy()` para que al cambiar el valor en `B`, el array original `A` **no** se vea afectado.

In [ ]:
# Espacio para tus respuestas de la Sección 4

### Sección 5: Creación de Arrays Especiales (`ones`, `zeros`, `identity`, `eye`)

1.  **`zeros_like`:** Crea un array de ceros que tenga la misma forma y tipo de dato que la matriz `M` de la sección 3.
2.  **`identity`:** Crea una matriz identidad de 4x4.
3.  **`eye`:** Crea una matriz de 6x5 donde la diagonal de unos esté desplazada una posición hacia arriba.

In [ ]:
# Espacio para tus respuestas de la Sección 5

### Pregunta Conceptual

* Explica con tus propias palabras por qué la función `numpy_version()` del notebook es significativamente más rápida que `pure_python_version()`, a pesar de que ambas realizan la misma suma de vectores.

*(Escribe tu respuesta aquí)*

### ⭐ Desafío

* Crea una matriz `C` de 10x10 que contenga únicamente ceros. Luego, utilizando slicing, modifica la matriz `C` para que tenga un "marco" de unos.

In [ ]:
# Espacio para tu respuesta al desafío