```
                                                                    .___ ______________________  _________________
                                                                    |   |\__    ___/\_   _____/ /   _____/\_____  \
                                                                    |   |  |    |    |    __)_  \_____  \  /   |   \
                                                                    |   |  |    |    |        \ /        \/    |    \
                                                                    |___|  |____|   /_______  //_______  /\_______  /
                                                                                            \/         \/         \/
```
<div class="alert alert-block alert-info">
<span style="color: rgb(0,53,91);">
<font face = "Times New Roman" size = "6"><b><center>Programacion para Mineria de Datos</center></b></font>
<font face = "Times New Roman" size = "5"><b><center>EJERCICIO_NUMPY_RANDOM</center></b></font>

<b><font back = "Times New Roman" size = "4"><center>Unidad 3: </center></font>

<div align="right"><font face = "Times New Roman" size = "2">Mtro. Miguel Tlapa Juarez (migueltlapa@iteso.mx)</font></div>
</span></div>

# Ejercicios Prácticos de NumPy: Arrays

**Instrucciones:** Utiliza tus conocimientos de NumPy para resolver los siguientes problemas. Escribe el código necesario en las celdas correspondientes para obtener el resultado solicitado.

### Sección 1: Generación de Números Aleatorios

1.  **Entero único:** Simula el lanzamiento de un dado de 6 caras. Genera un único número entero aleatorio entre 1 y 6 (ambos inclusive).
2.  **Array de flotantes:** Crea un array de NumPy con 8 números flotantes aleatorios, donde cada número esté entre 0.0 y 1.0.
3.  **Matriz de enteros:** Crea una matriz (array 2D) de 3x4 que contenga números enteros aleatorios entre 10 y 50 (sin incluir el 50).

In [1]:
import numpy as np
import random

# Espacio para tus respuestas de la Sección 1

# 1. Entero único: Simula el lanzamiento de un dado de 6 caras
dado = np.random.randint(1, 7)
print(f"Resultado del dado: {dado}")

# 2. Array de flotantes: 8 números flotantes aleatorios entre 0.0 y 1.0
array_flotantes = np.random.random(8)
print(f"Array de flotantes: {array_flotantes}")

# 3. Matriz de enteros: 3x4 con números enteros aleatorios entre 10 y 50 (sin incluir 50)
matriz_enteros = np.random.randint(10, 50, size=(3, 4))
print(f"Matriz de enteros 3x4:\n{matriz_enteros}")

Resultado del dado: 6
Array de flotantes: [0.88005442 0.39786185 0.23057585 0.32309166 0.52472787 0.46470086
 0.38358856 0.67920582]
Matriz de enteros 3x4:
[[34 44 45 32]
 [34 10 16 40]
 [14 38 13 37]]


### Sección 2: Elecciones Aleatorias de una Lista

Usa la siguiente lista de `posibles_premios` para los ejercicios de esta sección:

In [2]:
posibles_premios = ["Coche", "Viaje", "Laptop", "Smartphone", "Nada", "Tablet"]

1.  **Elección única:** Elige un premio al azar de la lista `posibles_premios`.
2.  **Múltiples elecciones (con reemplazo):** Simula 5 sorteos de premios. Crea un array de NumPy que contenga 5 elecciones al azar de la lista. En esta simulación, un mismo premio puede salir varias veces.
3.  **Múltiples elecciones (sin reemplazo):** Elige 3 premios **únicos** de la lista. Ningún premio debe repetirse en el resultado.

In [3]:
# Espacio para tus respuestas de la Sección 2

# 1. Elección única: Elige un premio al azar de la lista posibles_premios
premio_unico = np.random.choice(posibles_premios)
print(f"Premio único: {premio_unico}")

# 2. Múltiples elecciones (con reemplazo): 5 sorteos de premios
sorteos_con_reemplazo = np.random.choice(posibles_premios, size=5, replace=True)
print(f"5 sorteos con reemplazo: {sorteos_con_reemplazo}")

# 3. Múltiples elecciones (sin reemplazo): 3 premios únicos
premios_unicos = np.random.choice(posibles_premios, size=3, replace=False)
print(f"3 premios únicos: {premios_unicos}")

Premio único: Tablet
5 sorteos con reemplazo: ['Tablet' 'Laptop' 'Nada' 'Smartphone' 'Coche']
3 premios únicos: ['Tablet' 'Smartphone' 'Coche']


### Sección 3: Reproducibilidad (Semilla Aleatoria)

1.  **Generación con semilla:** Usando el módulo `random`, establece una semilla aleatoria con el valor `123`. Luego, genera y muestra una lista de 5 números enteros aleatorios entre 1 y 100.
2.  **Comprobación de reproducibilidad:** En la misma celda, vuelve a establecer la semilla a `123` y genera otra vez 5 números enteros aleatorios entre 1 y 100. El resultado debería ser idéntico al anterior.

In [4]:
# Espacio para tus respuestas de la Sección 3

# 1. Generación con semilla
random.seed(123)
numeros_primera_vez = [random.randint(1, 100) for _ in range(5)]
print(f"Primera generación con semilla 123: {numeros_primera_vez}")

# 2. Comprobación de reproducibilidad
random.seed(123)
numeros_segunda_vez = [random.randint(1, 100) for _ in range(5)]
print(f"Segunda generación con semilla 123: {numeros_segunda_vez}")

# Verificar que son iguales
print(f"¿Los resultados son idénticos? {numeros_primera_vez == numeros_segunda_vez}")

Primera generación con semilla 123: [7, 35, 12, 99, 53]
Segunda generación con semilla 123: [7, 35, 12, 99, 53]
¿Los resultados son idénticos? True


### Sección 4: Aplicaciones y Preguntas Conceptuales

1.  **Normalización a 1:** Imagina que tienes un presupuesto de $1 que debes distribuir aleatoriamente entre 5 proyectos. Crea un array de NumPy con 5 números aleatorios y luego normalízalos para que su suma sea exactamente 1.0.
2.  **Pregunta conceptual:** Basado en el notebook, ¿cuándo y por qué preferirías usar `numpy.random` en lugar del módulo `random` de Python estándar?

In [5]:
# Espacio para tu respuesta 4.1

# 1. Normalización a 1: Distribuir $1 entre 5 proyectos
presupuestos_aleatorios = np.random.random(5)
print(f"Números aleatorios originales: {presupuestos_aleatorios}")

# Normalizar para que sumen exactamente 1.0
presupuestos_normalizados = presupuestos_aleatorios / presupuestos_aleatorios.sum()
print(f"Presupuestos normalizados: {presupuestos_normalizados}")
print(f"Suma total: {presupuestos_normalizados.sum()}")
print(f"Cada proyecto recibe: {presupuestos_normalizados * 100}% del presupuesto")

Números aleatorios originales: [0.89665979 0.48189465 0.75110628 0.01376234 0.81992903]
Presupuestos normalizados: [0.30258294 0.16261809 0.25346508 0.00464418 0.27668971]
Suma total: 1.0
Cada proyecto recibe: [30.25829407 16.26180879 25.34650819  0.46441808 27.66897086]% del presupuesto


**Respuesta conceptual para la pregunta 4.2:**

Preferiría usar `numpy.random` en lugar del módulo `random` de Python estándar en las siguientes situaciones:

1. **Trabajando con arrays de NumPy**: `numpy.random` está diseñado específicamente para trabajar con arrays de NumPy y puede generar directamente arrays multidimensionales de números aleatorios, mientras que el módulo `random` de Python genera valores individuales.

2. **Rendimiento**: `numpy.random` es significativamente más rápido para generar grandes cantidades de números aleatorios debido a que está implementado en C y optimizado para operaciones vectorizadas.

3. **Operaciones vectorizadas**: Cuando necesito generar muchos números aleatorios de una vez (por ejemplo, una matriz completa), `numpy.random` puede hacerlo en una sola operación, mientras que con `random` tendría que usar bucles o list comprehensions.

4. **Integración con el ecosistema científico**: Al trabajar con bibliotecas como NumPy, SciPy, Pandas, etc., `numpy.random` se integra mejor y mantiene la consistencia en el tipo de datos (arrays de NumPy).

5. **Funciones especializadas**: `numpy.random` ofrece distribuciones estadísticas más avanzadas (normal, binomial, poisson, etc.) que son comunes en análisis científico y de datos.

### ⭐ Desafío

Simula el lanzamiento de una moneda 1000 veces. La moneda no está trucada (50% de probabilidad para cara y 50% para cruz).

1.  Genera un array de NumPy que represente los 1000 lanzamientos (puedes usar 0 para cruz y 1 para cara).
2.  Cuenta y muestra cuántas veces salió cara y cuántas veces salió cruz.

In [6]:
# Espacio para tu respuesta al desafío

# Simulación de lanzamiento de moneda 1000 veces
# 0 = cruz, 1 = cara

lanzamientos = np.random.randint(0, 2, size=1000)
print(f"Primeros 20 lanzamientos: {lanzamientos[:20]}")

# Contar resultados
caras = np.sum(lanzamientos == 1)
cruces = np.sum(lanzamientos == 0)

print(f"\nResultados de 1000 lanzamientos:")
print(f"Caras (1): {caras} veces ({caras/1000*100:.1f}%)")
print(f"Cruces (0): {cruces} veces ({cruces/1000*100:.1f}%)")
print(f"Total: {caras + cruces} lanzamientos")

# Verificación adicional
print(f"\nVerificación: {len(lanzamientos)} lanzamientos realizados")

Primeros 20 lanzamientos: [1 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 1 1 0 1]

Resultados de 1000 lanzamientos:
Caras (1): 522 veces (52.2%)
Cruces (0): 478 veces (47.8%)
Total: 1000 lanzamientos

Verificación: 1000 lanzamientos realizados
