```
                                                                    .___ ______________________  _________________
                                                                    |   |\__    ___/\_   _____/ /   _____/\_____  \
                                                                    |   |  |    |    |    __)_  \_____  \  /   |   \
                                                                    |   |  |    |    |        \ /        \/    |    \
                                                                    |___|  |____|   /_______  //_______  /\_______  /
                                                                                            \/         \/         \/
```
<div class="alert alert-block alert-info">
<span style="color: rgb(0,53,91);">
<font face = "Times New Roman" size = "6"><b><center>Programacion para Mineria de Datos</center></b></font>
<font face = "Times New Roman" size = "5"><b><center>EJERCICIO_NUMPY_READ_FILES</center></b></font>

<b><font back = "Times New Roman" size = "4"><center>Unidad 3: </center></font>

<div align="right"><font face = "Times New Roman" size = "2">Mtro. Miguel Tlapa Juarez (migueltlapa@iteso.mx)</font></div>
</span></div>

# Ejercicios Prácticos de NumPy: Lectura y Escritura de Archivos

**Instrucciones:** Utiliza tus conocimientos de NumPy para resolver los siguientes problemas de manipulación de archivos. Escribe el código necesario en las celdas correspondientes.

### Sección 1: Guardar y Cargar Archivos de Texto (`savetxt`, `loadtxt`, `genfromtxt`)

In [2]:
import numpy as np

# Este es el array que usaremos para los primeros ejercicios.
mi_array = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print("Array original:")
print(mi_array)

Array original:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


1.  **Guardado simple:** Guarda el `mi_array` en un archivo de texto llamado `mi_matriz.txt` con el formato estándar.
2.  **Carga simple:** Carga los datos del archivo `mi_matriz.txt` en una nueva variable llamada `matriz_cargada` y muéstrala en pantalla para verificar que se leyó correctamente.
3.  **Guardado con formato:** Guarda de nuevo `mi_array`, pero esta vez en un archivo llamado `matriz_formateada.csv`. Utiliza una coma (`,`) como delimitador y formatea los números como enteros de 3 dígitos con ceros a la izquierda (por ejemplo, `5` debe guardarse como `005`).
4.  **Carga selectiva:** Utilizando `np.genfromtxt`, carga los datos de `matriz_formateada.csv`, pero esta vez, lee únicamente la **primera y la última columna**.

In [3]:
# Espacio para tus respuestas de la Sección 1

### Sección 2: Trabajar con Archivos Binarios (`tofile`, `fromfile`)

Los archivos binarios son más eficientes para almacenar datos numéricos, aunque no son legibles por humanos.

1.  **Guardado binario:** Crea un array de NumPy con los números del 0 al 19. Guarda este array en un archivo binario llamado `datos.bin`.
2.  **Lectura binaria:** Lee los datos del archivo `datos.bin` y cárgalos en una nueva variable.
3.  **Importante:** Recuerda que al leer un archivo binario con `np.fromfile`, debes especificar el `dtype` (tipo de dato) con el que se guardaron los datos.

In [6]:
# Espacio para tus respuestas de la Sección 2

### Sección 3: Guardar Objetos con `pickle`

Pickle es una forma de guardar objetos completos de Python (incluyendo arrays de NumPy) en un archivo.

1.  **Guardar con `pickle`:** Crea una matriz de NumPy de 2x2 con los números que prefieras. Utiliza el módulo `pickle` para guardar este objeto en un archivo llamado `mi_pickle.pkl`.
2.  **Cargar con `pickle`:** Carga el objeto desde `mi_pickle.pkl` en una nueva variable. Imprime la variable y su tipo (`type()`) para verificar que se ha recuperado el array de NumPy correctamente.

In [7]:
# Espacio para tus respuestas de la Sección 3