```
                                                                    .___ ______________________  _________________
                                                                    |   |\__    ___/\_   _____/ /   _____/\_____  \
                                                                    |   |  |    |    |    __)_  \_____  \  /   |   \
                                                                    |   |  |    |    |        \ /        \/    |    \
                                                                    |___|  |____|   /_______  //_______  /\_______  /
                                                                                            \/         \/         \/
```
<div class="alert alert-block alert-info">
<span style="color: rgb(0,53,91);">
<font face = "Times New Roman" size = "6"><b><center>Programacion para Mineria de Datos</center></b></font>
<font face = "Times New Roman" size = "5"><b><center>EJERCICIO_2_NUMPY_ARRAY</center></b></font>

<b><font back = "Times New Roman" size = "4"><center>Unidad 3: </center></font>

<div align="right"><font face = "Times New Roman" size = "2">Mtro. Miguel Tlapa Juarez (migueltlapa@iteso.mx)</font></div>
</span></div>



# Ejercicios Prácticos de NumPy: Arrays

**Instrucciones:** Utiliza tus conocimientos de NumPy para resolver los siguientes problemas. Escribe el código necesario en las celdas correspondientes para obtener el resultado solicitado.


### Sección 1: Creación de Arrays (`arange` y `linspace`)

### Sección 1: Generación de Números Aleatorios

1.  **Entero único:** Simula el lanzamiento de un dado de 6 caras. Genera un único número entero aleatorio entre 1 y 6 (ambos inclusive).
2.  **Array de flotantes:** Crea un array de NumPy con 8 números flotantes aleatorios, donde cada número esté entre 0.0 y 1.0.
3.  **Matriz de enteros:** Crea una matriz (array 2D) de 3x4 que contenga números enteros aleatorios entre 10 y 50 (sin incluir el 50).

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=42)

dado = rng.integers(1, 7)

array_floats = rng.random(8)

matriz_enteros = rng.integers(10, 50, size=(3, 4))

print("1) Lanzamiento de dado (1–6):", dado)
print("\n2) Array de 8 flotantes [0,1):\n", array_floats)
print("\n3) Matriz 3x4 de enteros [10,49]:\n", matriz_enteros)


1) Lanzamiento de dado (1–6): 1

2) Array de 8 flotantes [0,1):
 [0.43887844 0.85859792 0.69736803 0.09417735 0.97562235 0.7611397
 0.78606431 0.12811363]

3) Matriz 3x4 de enteros [10,49]:
 [[40 43 28 30]
 [24 17 47 41]
 [35 26 42 31]]


### Sección 2: Dimensiones y Forma (`ndim`, `shape` y `reshape`)

1.  **Creación y análisis 2D:**
    * Crea un array 2D (una matriz) de 3 filas y 4 columnas con los números del 0 al 11.
    * Imprime la forma (`shape`) del array.
    * Imprime el número de dimensiones (`ndim`) del array.
2.  **Creación y análisis 3D:**
    * Crea un array 3D de dimensiones (2, 3, 2) utilizando los números del 0 al 11.
    * Imprime su forma y el número de dimensiones.

In [8]:
# Espacio para tus respuestas de la Sección 2
import numpy as np

# 1) Creación y análisis 2D
arr2d = np.arange(12).reshape(3, 4)
print("Array 2D (3x4):\n", arr2d)
print("shape (2D):", arr2d.shape)  # -> (3, 4)
print("ndim (2D):", arr2d.ndim)    # -> 2

# 2) Creación y análisis 3D
arr3d = np.arange(12).reshape(2, 3, 2)
print("\nArray 3D (2,3,2):\n", arr3d)
print("shape (3D):", arr3d.shape)  # -> (2, 3, 2)
print("ndim (3D):", arr3d.ndim)    # -> 3


Array 2D (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape (2D): (3, 4)
ndim (2D): 2

Array 3D (2,3,2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
shape (3D): (2, 3, 2)
ndim (3D): 3


### Sección 3: Indexación y Slicing

Para los siguientes ejercicios, utiliza el array `M` que se define en la celda de abajo:

In [9]:
M = np.arange(25).reshape(5, 5)
print("Array M:")
print(M)

Array M:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


1.  **Elemento específico:** Obtén el número `18` del array `M`.
2.  **Fila completa:** Obtén la segunda fila completa del array `M` (la que contiene los números del 5 al 9).
3.  **Columna completa:** Obtén la última columna del array `M` (la que contiene 4, 9, 14, 19, 24).
4.  **Submatriz (Slicing 2D):** Obtén la submatriz que contiene los números:
    ```
    [[11, 12],
     [16, 17]]
    ```
5.  **Slicing con pasos:** A partir de `M`, obtén el siguiente resultado saltando filas y columnas:
    ```
    [[ 0  2  4],
     [10 12 14],
     [20 22 24]]
    ```

In [ ]:
# Espacio para tus respuestas de la Sección 3
import numpy as np

M = np.arange(25).reshape(5, 5)
print("Array M:")
print(M)

print("\n1) M[3, 3] =", M[3, 3])

print("\n2) M[1, :] =", M[1, :])

print("\n3) M[:, -1] =", M[:, -1])

print("\n4) M[2:4, 1:3] =\n", M[2:4, 1:3])

print("\n5) M[::2, ::2] =\n", M[::2, ::2])


Array M:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

1) M[3, 3] = 18

2) M[1, :] = [5 6 7 8 9]

3) M[:, -1] = [ 4  9 14 19 24]

4) M[2:4, 1:3] =
 [[11 12]
 [16 17]]

5) M[::2, ::2] =
 [[ 0  2  4]
 [10 12 14]
 [20 22 24]]


### Sección 4: Vistas vs. Copias

1.  **Predice el resultado:** Observa el siguiente código. ¿Qué se imprimirá al final? Explica brevemente por qué.
    ```python
    A = np.arange(10)
    B = A[3:7]
    B[0] = 99
    print(A)
    ```
    ***Respuesta :*** B = A[3:7] es un slice que devuelve una vista (no una copia) de A. Al hacer B[0] = 99, en realidad modificas A[3], porque ambos comparten el mismo buffer de memoria.
2.  **Soluciona el problema:** Modifica el código anterior utilizando `.copy()` para que al cambiar el valor en `B`, el array original `A` **no** se vea afectado.

In [ ]:
# Espacio para tus respuestas de la Sección 4
import numpy as np

A = np.arange(10)
B = A[3:7].copy()
B[0] = 99

print(A)
print(B) 


[0 1 2 3 4 5 6 7 8 9]
[99  4  5  6]


### Sección 5: Creación de Arrays Especiales (`ones`, `zeros`, `identity`, `eye`)

1.  **`zeros_like`:** Crea un array de ceros que tenga la misma forma y tipo de dato que la matriz `M` de la sección 3.
2.  **`identity`:** Crea una matriz identidad de 4x4.
3.  **`eye`:** Crea una matriz de 6x5 donde la diagonal de unos esté desplazada una posición hacia arriba.

In [ ]:
# Espacio para tus respuestas de la Sección 5
import numpy as np

M = np.arange(25).reshape(5, 5)

zeros_M = np.zeros_like(M)

I4 = np.identity(4)

E_6x5 = np.eye(6, 5, k=1)

print("1) ceros(M):\n", zeros_M)
print("\n2) identidad(4):\n", I4)
print("\n3) eye(6, 5, k=1):\n", E_6x5)


1) zeros_like(M):
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

2) identity(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

3) eye(6, 5, k=1):
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Pregunta Conceptual

* Explica con tus propias palabras por qué la función `numpy_version()` del notebook es significativamente más rápida que `pure_python_version()`, a pesar de que ambas realizan la misma suma de vectores.

*(Porque python es interpretado, y lo que pasa es que python va ejecutando linea por linea, esto hace que el interprete este verificando cada linea, tambien las variables pueden cambiar entre enteros o strings, entonces debe de hacer comparación en cada linea si no cambio, en cambio numpy corre en C que es un lenguaje mas estricto, y eficiente, esto quiere decir que hay que se crea con tipos fijos y memoria contigua.)*

### ⭐ Desafío

* Crea una matriz `C` de 10x10 que contenga únicamente ceros. Luego, utilizando slicing, modifica la matriz `C` para que tenga un "marco" de unos.

In [26]:
# Espacio para tu respuesta al desafío
import numpy as np

# 1) Crear matriz 10x10 de ceros (entera)
C = np.zeros((10, 10), dtype=int)

# 2) "Marco" de unos con slicing
C[0, :]  = 1   # fila superior
C[-1, :] = 1   # fila inferior
C[:, 0]  = 1   # columna izquierda
C[:, -1] = 1   # columna derecha

print(C)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]
